{
 "title": "Shopmate-dashboard",
 "time": { "from": "2025-08-21T03:48:03.579Z", "to": "2025-08-21T05:43:13.841Z" },
 "panels": [
  {
   "title": "Memory Usage % (512MB allocated)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "ClusterName": "shopbot-ecs-dev", "ServiceName": "shopbot-service-dev" },
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "ap-southeast-1",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "CPU Usage % (256 CPU units allocated)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "ClusterName": "shopbot-ecs-dev", "ServiceName": "shopbot-service-dev" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "ap-southeast-1",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Stress Load req/sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_requests_total{route=\"/stress\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "App Memory Usage (MB)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "nodejs_process_resident_memory_bytes / 1024 / 1024",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "Container Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 13, "y": 7 },
   "targets": [
    {
     "dimensions": { "ClusterName": "shopbot-ecs-dev", "ServiceName": "shopbot-service-dev" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "ap-southeast-1",
     "statistic": "SampleCount"
    }
   ]
  }
 ]
}